name: email_detector
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip>=21.0
  - numpy>=1.20.0
  - pandas>=1.3.3
  - scikit-learn>=1.0
  - jupyter>=1.0.0
  - matplotlib>=3.4.0
  - scipy>=1.7.0
  - pip:
    - dnspython>=2.1.0
    - python-whois>=0.7.3
    - tqdm>=4.62.0
    - fastapi>=0.68.0
    - uvicorn>=0.15.0
